### ISSUE TITLE
TypeError when creating a budget alert rule

### ISSUE THREAD

**Issue by mortenlj** [oracle/oci-ansible-collection#120] opened 2021-10-30 19:38 UTC
## Issue Report

**Describe the issue**

When trying to create a budget alert rule, ansible fails with a TypeError:

`TypeError: systemd.journal.send() got multiple values for keyword argument 'MESSAGE'`

**Expected behavior**

I expected a budget alert rule to be created

**Environment**

* OS version: Ubuntu 21.04

* Ansible version:

ansible 2.10.5
  config file = /home/mortenlj/.ansible.cfg
  configured module search path = ['/home/mortenlj/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.5 (default, May 11 2021, 08:20:37) [GCC 10.3.0]

* OCI Python SDK version:

2.48.0

* OCI Ansible Modules version:

oracle.oci           2.33.0 

**Ansible playbook to reproduce the issue**

```
---
- name : Test budget alert
  collections:
    - oracle.oci
  connection: local
  hosts: localhost
  tasks:
    - name: Max budget of one NOK
      oracle.oci.oci_budget:
        compartment_id: "{{ compartment_id }}"
        amount: 1
        display_name: free
        description: Free as in beer
        reset_period: MONTHLY
        target_type: COMPARTMENT
        targets:
          - "{{ compartment_id }}"
      register: budget
    - name: Alert when forcasted spend is above budget
      oracle.oci.oci_budget_alert_rule:
        budget_id: "{{ budget.budget.id }}"
        description: Warn if we are spending
        display_name: free-alert
        message: "We are spending money on Oracle Cloud"
        recipients: sample_recipient
        threshold: 50
        threshold_type: PERCENTAGE
        type: FORECAST
```

**Comment by dineshsuthar786** [comment] 2021-11-13 06:10
@mortenlj, Thanks for reporting the issue. I am not able to reproduce the issue. Could you please increase the verbosity by passing `-vvv` and enable the debug logs by following the steps [here](https://github.com/oracle/oci-ansible-collection/blob/master/FAQ.md) about “how to enable debug mode” and share verbosity & debug logs with us.

**Comment by mortenlj** [comment] 2021-11-13 10:31
Here are the logs. I will also edited the test-play in the original comment to include everything, not just the tasks. Maybe I'm doing something wrong at the playbook-level.

[ansible_output.log](https://github.com/oracle/oci-ansible-collection/files/7531824/ansible_output.log)
[oci_ansible_module.log](https://github.com/oracle/oci-ansible-collection/files/7531825/oci_ansible_module.log)

**Comment by rohnigam** [comment] 2021-11-16 06:50
hey @mortenlj 

Thanks for sharing the logs.

We are checking them.

**Comment by rohnigam** [comment] 2021-11-17 08:34
hey @mortenlj 

This looks like an issue with base ansible when linux systemd.journal is enabled and the ansible module has a 'message' field.

This has been reported before to ansible ([check this](https://github.com/ansible/ansible/issues/47132)).

This will require some fix on our side since ansible will not change its implementation.
We are currently looking at this in the backend how best to handle this.

We'll keep you posted.

**Comment by rohan033** [comment] 2021-12-06 08:38
@mortenlj This is fixed in v.2.36.0 . You can check https://docs.oracle.com/en-us/iaas/tools/oci-ansible-collection/2.36.0/collections/oracle/oci/oci_budget_alert_rule_module.html#ansible-collections-oracle-oci-oci-budget-alert-rule-module

**Closed by rohan033** 2021-12-06 08:38 UTC
