### ISSUE TITLE
How to list all block volumes attached to a compute instance

### ISSUE THREAD

**Issue by DII-dsward** [oracle/oci-ansible-collection#130] opened 2021-11-18 17:30 UTC
## Issue Report

**Describe the issue**

Need to push cost tracking tags to our boot and block volumes attached to a VM. I do not see references to which VM these disks are attached to in the oci_blockstorage_volume_facts, oci_blockstorage_boot_volume_facts, or the oci_compute_instance_facts.

**Expected behavior**

oci_blockstorage_volume_facts and oci_blockstorage_boot_volume_facts modules should reference the OCID of the compute instances they are attached to.

oci_compute_instance_facts module should reference all attached boot and block volumes

**Environment**

* OS version:
requirements.yml
```yaml
---
collections:
  - name: oracle.oci
    version: 2.35.0
```

* Ansible version:
```
[user@awx~]$ ansible --version
ansible 2.9.19
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user1/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Sep  9 2021, 07:49:02) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
[user@awx~]$
```

* OCI Python SDK version:

```
[user@awx~]$ python3 -c "import oci;print(oci.__version__)"
2.46.0
```

* OCI Ansible Modules version:

```
(ansible) [user@awx ~]$ ansible-galaxy collection list
usage: ansible-galaxy collection [-h] COLLECTION_ACTION ...
ansible-galaxy collection: error: argument COLLECTION_ACTION: invalid choice: 'list' (choose from 'init', 'build', 'publish', 'install')
(ansible) [user@awx ~]$ 
```

**Ansible playbook to reproduce the issue**
Playbook Sample for oci_blockstorage_boot_volume_facts
```yaml 
- name: Get a specific boot_volume
  oci_blockstorage_boot_volume_facts:
    boot_volume_id: "ocid1.bootvolume.oc1..xxxxxxEXAMPLExxxxxx"
```
Expected output for oci_blockstorage_boot_volume_facts
```json
 sample: [{
        "availability_domain": "Uocm:PHX-AD-1",
        "compartment_id": "ocid1.compartment.oc1..xxxxxxEXAMPLExxxxxx",
        "defined_tags": {'Operations': {'CostCenter': 'US'}},
        "system_tags": {},
        "display_name": "display_name_example",
        "freeform_tags": {'Department': 'Finance'},
        "id": "ocid1.resource.oc1..xxxxxxEXAMPLExxxxxx",
        "image_id": "ocid1.image.oc1..xxxxxxEXAMPLExxxxxx",
        "is_hydrated": true,
        "vpus_per_gb": 56,
        "lifecycle_state": "PROVISIONING",
        "size_in_gbs": 56,
        "size_in_mbs": 56,
        "source_details": {
            "type": "bootVolume",
            "id": "ocid1.resource.oc1..xxxxxxEXAMPLExxxxxx"
        },
        "time_created": "2013-10-20T19:20:30+01:00",
        "volume_group_id": "ocid1.volumegroup.oc1..xxxxxxEXAMPLExxxxxx",
        "kms_key_id": "ocid1.kmskey.oc1..xxxxxxEXAMPLExxxxxx",
        "is_auto_tune_enabled": true,
        "auto_tuned_vpus_per_gb": 56,
        "boot_volume_replicas": [{
            "display_name": "display_name_example",
            "boot_volume_replica_id": "ocid1.bootvolumereplica.oc1..xxxxxxEXAMPLExxxxxx",
            "availability_domain": "Uocm:PHX-AD-1"
        }],
        "attached_compute_instances": [{
            "compute_instance_id: "ocid1.instance.oc1..xxxxxxEXAMPLE1xxxxxx",
            "compute_instance_name: "VM1",
            "compute_instance_attachment: "iSCSI"
        },
            "compute_instance_id: "ocid1.instance.oc1..xxxxxxEXAMPLE2xxxxxx",
            "compute_instance_name: "VM2",
            "compute_instance_attachment: "Paravirtualized"
        }]
    }]
```
Playbook Sample for oci_blockstorage_boot_volume_facts
```yaml
- name: Get a specific boot_volume
  oci_blockstorage_boot_volume_facts:
    boot_volume_id: "ocid1.bootvolume.oc1..xxxxxxEXAMPLExxxxxx"
```
Expected output for oci_blockstorage_boot_volume_facts
```json
sample: [{
        "availability_domain": "Uocm:PHX-AD-1",
        "compartment_id": "ocid1.compartment.oc1..xxxxxxEXAMPLExxxxxx",
        "defined_tags": {'Operations': {'CostCenter': 'US'}},
        "system_tags": {},
        "display_name": "display_name_example",
        "freeform_tags": {'Department': 'Finance'},
        "id": "ocid1.resource.oc1..xxxxxxEXAMPLExxxxxx",
        "image_id": "ocid1.image.oc1..xxxxxxEXAMPLExxxxxx",
        "is_hydrated": true,
        "vpus_per_gb": 56,
        "lifecycle_state": "PROVISIONING",
        "size_in_gbs": 56,
        "size_in_mbs": 56,
        "source_details": {
            "type": "bootVolume",
            "id": "ocid1.resource.oc1..xxxxxxEXAMPLExxxxxx"
        },
        "time_created": "2013-10-20T19:20:30+01:00",
        "volume_group_id": "ocid1.volumegroup.oc1..xxxxxxEXAMPLExxxxxx",
        "kms_key_id": "ocid1.kmskey.oc1..xxxxxxEXAMPLExxxxxx",
        "is_auto_tune_enabled": true,
        "auto_tuned_vpus_per_gb": 56,
        "boot_volume_replicas": [{
            "display_name": "display_name_example",
            "boot_volume_replica_id": "ocid1.bootvolumereplica.oc1..xxxxxxEXAMPLExxxxxx",
            "availability_domain": "Uocm:PHX-AD-1"
        }],
        "attached_compute_instances": [{
            "compute_instance_id: "ocid1.instance.oc1..xxxxxxEXAMPLE1xxxxxx",
            "compute_instance_name: "VM1"
        }]
    }]
```
Playbook Sample for oci_compute_instance_facts
```yaml
- name: Get a specific instance
  oci_compute_instance_facts:
    instance_id: "ocid1.instance.oc1..xxxxxxEXAMPLExxxxxx"
```
Expected output for oci_compute_instance_facts
```json
    sample: [{
        "availability_domain": "Uocm:PHX-AD-1",
        "capacity_reservation_id": "ocid1.capacityreservation.oc1..xxxxxxEXAMPLExxxxxx",
        "compartment_id": "ocid1.compartment.oc1..xxxxxxEXAMPLExxxxxx",
        "dedicated_vm_host_id": "ocid1.dedicatedvmhost.oc1..xxxxxxEXAMPLExxxxxx",
        "defined_tags": {'Operations': {'CostCenter': 'US'}},
        "display_name": "My bare metal instance",
        "extended_metadata": {},
        "fault_domain": "FAULT-DOMAIN-1",
        "freeform_tags": {'Department': 'Finance'},
        "id": "ocid1.resource.oc1..xxxxxxEXAMPLExxxxxx",
        "image_id": "ocid1.image.oc1..xxxxxxEXAMPLExxxxxx",
        "ipxe_script": "ipxe_script_example",
        "launch_mode": "NATIVE",
        "launch_options": {
            "boot_volume_type": "ISCSI",
            "firmware": "BIOS",
            "network_type": "E1000",
            "remote_data_volume_type": "ISCSI",
            "is_pv_encryption_in_transit_enabled": true,
            "is_consistent_volume_naming_enabled": true
        },
        "instance_options": {
            "are_legacy_imds_endpoints_disabled": true
        },
        "availability_config": {
            "is_live_migration_preferred": true,
            "recovery_action": "RESTORE_INSTANCE"
        },
        "preemptible_instance_config": {
            "preemption_action": {
                "type": "TERMINATE",
                "preserve_boot_volume": true
            }
        },
        "lifecycle_state": "MOVING",
        "metadata": {},
        "region": "region_example",
        "shape": "shape_example",
        "shape_config": {
            "ocpus": 3.4,
            "memory_in_gbs": 3.4,
            "baseline_ocpu_utilization": "BASELINE_1_8",
            "processor_description": "processor_description_example",
            "networking_bandwidth_in_gbps": 3.4,
            "max_vnic_attachments": 56,
            "gpus": 56,
            "gpu_description": "gpu_description_example",
            "local_disks": 56,
            "local_disks_total_size_in_gbs": 3.4,
            "local_disk_description": "local_disk_description_example"
        },
        "source_details": {
            "source_type": "bootVolume",
            "boot_volume_id": "ocid1.bootvolume.oc1..xxxxxxEXAMPLExxxxxx",
            "boot_volume_size_in_gbs": 56,
            "image_id": "ocid1.image.oc1..xxxxxxEXAMPLExxxxxx",
            "kms_key_id": "ocid1.kmskey.oc1..xxxxxxEXAMPLExxxxxx"
        },
        "system_tags": {},
        "time_created": "2016-08-25T21:10:29.600Z",
        "agent_config": {
            "is_monitoring_disabled": true,
            "is_management_disabled": true,
            "are_all_plugins_disabled": true,
            "plugins_config": [{
                "name": "name_example",
                "desired_state": "ENABLED"
            }]
        },
        "time_maintenance_reboot_due": "2018-05-25T21:10:29.600Z",
        "platform_config": {
            "type": "AMD_MILAN_BM",
            "is_secure_boot_enabled": true,
            "is_trusted_platform_module_enabled": true,
            "is_measured_boot_enabled": true,
            "numa_nodes_per_socket": "NPS0"
        },
        "primary_private_ip": "10.0.0.10",
        "primary_public_ip": "140.34.93.209",
        "blockvolume_details": [{
            "source_type": "blockVolume",
            "block_volume_id": "ocid1.blockvolume.oc1..xxxxxxEXAMPLE1xxxxxx",
            "block_volume_name": "blockVolume1",
            "block_volume_size_in_gbs": 56,
            "kms_key_id": "ocid1.kmskey.oc1..xxxxxxEXAMPLE1xxxxxx"
        },
            "source_type": "blockVolume",
            "block_volume_id": "ocid1.blockvolume.oc1..xxxxxxEXAMPLE2xxxxxx",
            "block_volume_name": "blockVolume2",
            "block_volume_size_in_gbs": 1024,
            "kms_key_id": "ocid1.kmskey.oc1..xxxxxxEXAMPLE2xxxxxx"
        }]
    }]
```

**Comment by rohnigam** [comment] 2021-11-19 09:34
Hey @DII-dsward 

I understand your requirement but OCI Ansible SDK is just ansible sdk on top of APIs that the OCI services provide.

You should raise this requirement with the Service team.

**Comment by manojmeda** [comment] 2021-11-26 04:49
@DII-dsward Closing this issue since this is the expected behaviour. We generally don't deviate from the APIs so that we can release the modules quickly. Like @rohnigam suggested, you can create a feature request to the compute service team. And once the API adds support, all the OCI tools (including our modules) would support it.

**Closed by manojmeda** 2021-11-26 04:49 UTC
