### ISSUE TITLE
oci_file_storage_export_facts module return data does not include 'export_options'

### ISSUE THREAD

**Issue by DII-jkalbright** [oracle/oci-ansible-collection#126] opened 2021-11-11 16:40 UTC
- name: Get exports
      oci_file_storage_export_facts:
        lifecycle_state: "ACTIVE"
        region: "{{ item[0] }}"
        compartment_id: "{{ item[1].compartment_id }}"
      with_nested: 
        - '{{ oci_regions }}'
        - '{{ compartments["compartments"] }}'
      register: exports

The above ansible does not return any export options details for any of my exports despite options being configured.

The results:

                "exports": [
                    {
                        "export_set_id": "ocid1.exportset.oc1.iad.xxx",
                        "file_system_id": "ocid1.filesystem.oc1.iad.xxx",
                        "id": "ocid1.export.oc1.iad.xxx",
                        "lifecycle_state": "ACTIVE",
                        "path": "/xxx",
                        "time_created": "2020-09-15T19:44:21.783000+00:00"
                    },

According to the module documentation the return data should include a set of export options data.

**Environment**

* OCI Ansible Modules version:

2.32.0

**Comment by dineshsuthar786** [comment] 2021-11-12 05:52
Thanks for reporting this. we will check this and update you. Meanwhile can you share below information for debugging the issue.
- oci-python-sdk version { python -c "import oci;print(oci._version_)" }

**Comment by dineshsuthar786** [comment] 2021-11-13 05:06
@DII-jkalbright, `export_options` parameter is only returned for get operation. So, you can list all the exports first and then do get operation for `export_id` to fetch the export options for that export_id.

We have an internal issue to update the documentation for this. Let us know if you need any more help.

**Comment by manojmeda** [comment] 2021-11-26 05:08
@DII-jkalbright Closing this issue since this is the expected behaviour. We have an internal issue to update the documentation for this and any other module with this issue.

**Closed by manojmeda** 2021-11-26 05:08 UTC
