### ISSUE TITLE
oci_logging_log collection module does not clearly specify usage

### ISSUE THREAD

**Issue by joshmullis** [oracle/oci-ansible-collection#97] opened 2021-08-02 19:47 UTC
Hello,

The "archiving" parameter for the oci_logging_log module documentation states "True if archiving enabled. This field is now decrecated, you should use cloud flow to enable archiving", however I'm not sure exactly what "cloud flow" is or how to use it.

Is there another module I should be using?

Doc reference:  https://oci-ansible-collection.readthedocs.io/en/latest/collections/oracle/oci/oci_logging_log_module.html#ansible-collections-oracle-oci-oci-logging-log-module

```
configuration:
      archiving:
        is_enabled: yes
```

Thanks!
-josh

**Comment by rohan033** [comment] 2021-08-03 13:55
Hi @joshmullis 
You can check this link: https://docs.oracle.com/en-us/iaas/api/#/en/logging-management/20200531/datatypes/Archiving
Looks like it should be Service Connector Hub instead of cloud flow. We will check internally for if there was any documentation updates from the upstream service after we released the latest version.

**Comment by joshmullis** [comment] 2021-08-03 20:34
Thanks for that info.
I do have a conversation going with some people on your side to ensure this functionality doesn't go away.

In the meantime, I did notice that this ansible module does not change the archival setting if changed from "no" to "yes" and re-ran, however the documentation says it's updatable.

Can you guys possibly fix that in a future release?

**Comment by rohan033** [comment] 2021-08-04 14:05
Can you share the ansible-playbook for this task along with the debug logs. Add `-vvv` to the ansible-playbook and share the console logs. Also do share oci_ansible_log file (which is usually in the /tmp folder).

I will try to reproduce you issue and check. We will try to include any fix there in the upcoming releases as soon as possible.

**Comment by rohan033** [comment] 2021-09-07 05:54
We are not able to reproduce this issue. Closing this issue. If it still doesn't work then you can create a new issue with the required information (playbook, console log etc)

**Closed by rohan033** 2021-09-07 05:54 UTC
