### ISSUE TITLE
oci_loadbalancer_backend_set update deletes existing backends

### ISSUE THREAD

**Issue by saswamy** [oracle/oci-ansible-collection#13] opened 2020-07-31 04:25 UTC
with oci_loadbalancer_backend_set, 
    While trying to offline or drain existing backend set , it is DELETING ones which are not listed to drain or offline 

e.g : 
if backendset has 4 IPs : 
10.102.122.130
10.102.122.131
10.102.122.132
10.102.122.133

and if am offlining only 1 IP, oci_loadbalancer_backend_set module ends up deleting the remaining 3 not being specified while updating .

expected behaviour :   if am offlining only 1 IP, - it should offline the one IP and leave all others as is

**Comment by mross22** [comment] 2020-07-31 19:32
This behavior is by design, you can see an explanation in the migration guide (see entry for oci_loadbalancer_backend_set):
https://github.com/oracle/oci-ansible-collection/blob/master/MigrationGuide.md

When you execute a play using `oci_loadbalancer_backend_set` that specifies the `backends` parameter, the modules interpret that as the complete set of backends for that backend set.

If you want to update an individual backend, you should use the `oci_loadbalancer_backend` module instead.

**Comment by manojmeda** [comment] 2020-09-28 07:54
@saswamy Hopefully workaround given by @mross22 worked for you. Closing this issue. Please reopen if you still need anything from us.

**Closed by manojmeda** 2020-09-28 07:54 UTC
