### ISSUE TITLE
Listing of PDB's does not work.

### ISSUE THREAD

**Issue by danidorbek** [oracle/oci-ansible-collection#217] opened 2023-04-11 13:49 UTC
```yaml
    - name: List pluggable_databases
      oci_database_pluggable_database_facts:
        config_profile_name: "{{ conf_profile }}"
        compartment_id: "{{ compartment.lab }}"
        sort_by: PDBNAME
        sort_order: ASC
      register: reg_pdbs
```
returns error:
TASK [List pluggable_databases] ***********************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "error_code": "InvalidParameter", "http_response_status": "400", "module_documentation": "Refer to this link https://docs.oracle.com/en-us/iaas/tools/oci-ansible-collection/latest/collections/oracle/oci/oci_database_pluggable_database_facts_module.html", "msg": "**Listing resource failed with exception: Invalid pagination token**", "opc_request_id": "request_id_not_shown", "operation_name": "list_pluggable_databases", "request_endpoint": "GET https://database.eu-stockholm-1.oraclecloud.com/20160918/pluggableDatabases", "service_name": "database", "time": "2023-04-11T13:02:16.714239+00:00", "troubleshooting_tips": "Refer to troubleshooting guide https://docs.oracle.com/en-us/iaas/tools/oci-ansible-collection/latest/guides/troubleshooting-guide.html"}

.
Based on documentation there is no way to set pagination tokens when listing pluggable databases using ansible.

------------ Versions -----------
Collection Version
---------- -------
oracle.oci 4.18.0 

pip freeze | grep oci
oci==2.98.0

**Comment by manojmeda** [comment] 2023-04-11 14:26
@danidorbek Is this a one time error or does this happen consistently?
We use oci python SDK internally for pagination and it could be an error with that. To confirm, can you please provide the debug logs. You can check https://docs.oracle.com/en-us/iaas/tools/oci-ansible-collection/latest/guides/logging-guide.html on how to enable verbose mode and get debug logs.

**Comment by danidorbek** [comment] 2023-04-11 17:49
This error comes consistently. Ansible pdb list module seems lacking of pagination support.

<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/userhome/.ansible/tmp/ansible-tmp-1681234433.568032-3071574-14658543665006/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_oci_database_pluggable_database_facts_payload_0gx5y5ex/ansible_oci_database_pluggable_database_facts_payload.zip/ansible_collections/oracle/oci/plugins/module_utils/oci_resource_utils.py", line 208, in list
    resources = self.list_resources()
  File "/tmp/ansible_oci_database_pluggable_database_facts_payload_0gx5y5ex/ansible_oci_database_pluggable_database_facts_payload.zip/ansible_collections/oracle/oci/plugins/modules/oci_database_pluggable_database_facts.py", line 282, in list_resources
  File "/tmp/ansible_oci_database_pluggable_database_facts_payload_0gx5y5ex/ansible_oci_database_pluggable_database_facts_payload.zip/ansible_collections/oracle/oci/plugins/module_utils/oci_common_utils.py", line 217, in list_all_resources
    response = oci.pagination.list_call_get_all_results(target_fn, **kwargs)
  File "/home/userhome/venv39/lib64/python3.9/site-packages/oci/pagination/pagination_utils.py", line 205, in list_call_get_all_results
    for response in list_call_get_all_results_generator(list_func_ref, 'response', *list_func_args, **list_func_kwargs):
  File "/home/userhome/venv39/lib64/python3.9/site-packages/oci/pagination/pagination_utils.py", line 274, in list_call_get_all_results_generator
    call_result = retry.DEFAULT_RETRY_STRATEGY.make_retrying_call(list_func_ref, *list_func_args, **list_func_kwargs)
  File "/home/userhome/venv39/lib64/python3.9/site-packages/oci/retry/retry.py", line 308, in make_retrying_call
    response = func_ref(*func_args, **func_kwargs)
  File "/home/userhome/venv39/lib64/python3.9/site-packages/oci/database/database_client.py", line 24279, in list_pluggable_databases
    return self.base_client.call_api(
  File "/home/userhome/venv39/lib64/python3.9/site-packages/oci/base_client.py", line 485, in call_api
    response = self.request(request, allow_control_chars, operation_name, api_reference_link)
  File "/home/userhome/venv39/lib64/python3.9/site-packages/circuitbreaker.py", line 159, in wrapper
    return call(function, *args, **kwargs)
  File "/home/userhome/venv39/lib64/python3.9/site-packages/circuitbreaker.py", line 170, in call
    return func(*args, **kwargs)
  File "/home/userhome/venv39/lib64/python3.9/site-packages/oci/base_client.py", line 632, in request
    self.raise_service_error(request, response, service_code, message, operation_name, api_reference_link, target_service, request_endpoint, client_version, timestamp, deserialized_data)
  File "/home/userhome/venv39/lib64/python3.9/site-packages/oci/base_client.py", line 789, in raise_service_error
    raise exceptions.ServiceError(
fatal: [localhost]: FAILED! => {
    "changed": false,
    "error_code": "InvalidParameter",
    "http_response_status": "400",
    "invocation": {
        "module_args": {
            "api_user": null,
            "api_user_fingerprint": null,
            "api_user_key_file": null,
            "api_user_key_pass_phrase": null,
            "auth_purpose": null,
            "auth_type": "api_key",
            "cert_bundle": null,
            "compartment_id": "replaced",
            "config_file_location": null,
            "config_profile_name": "EXACC",
            "database_id": null,
            "lifecycle_state": null,
            "pdb_name": null,
            "pluggable_database_id": null,
            "region": null,
            "sort_by": "PDBNAME",
            "sort_order": "ASC",
            "tenancy": null
        }
    },
        "module_documentation": "Refer to this link https://docs.oracle.com/en-us/iaas/tools/oci-ansible-collection/latest/collections/oracle/oci/oci_database_pluggable_database_facts_module.html",
    "msg": "Listing resource failed with exception: Invalid pagination token",
    "oci_ansible_logs": [
        "2023-04-11,17:33:55 DEBUG oci_version_utils.py:46 Python Version: 3.9.13",
        "2023-04-11,17:33:55 DEBUG oci_version_utils.py:36 OCI-Python-Sdk version: 2.98.0",
        "2023-04-11,17:33:55 DEBUG oci_version_utils.py:55 Ansible Version: 2.12.0",
        "2023-04-11,17:33:55 DEBUG oci_version_utils.py:64 OCI-Ansible-Collections installed Version: 4.18.0",
        "2023-04-11,17:33:56 DEBUG oci_version_utils.py:85 OCI-Ansible-Collections latest version available: 4.18.0",
        "2023-04-11,17:33:56 DEBUG oci_version_utils.py:100 OCI-Python-Sdk path: ['/home/userhome/venv39/lib64/python3.9/site-packages/oci']",
        "2023-04-11,17:33:56 DEBUG oci_version_utils.py:110 Ansible module python path: ['/tmp/ansible_oci_database_pluggable_database_facts_payload_0gx5y5ex/ansible_oci_database_pluggable_database_facts_payload.zip/ansible', '/home/userhome/venv39/lib64/pyt
hon3.9/site-packages/ansible', '/home/userhome/venv39/lib/python3.9/site-packages/ansible']",
        "2023-04-11,17:33:56 DEBUG config.py:195 Config file found at ~/.oci/config",
        "2023-04-11,17:33:56 DEBUG base_client.py:348 Endpoint: https://database.eu-stockholm-1.oraclecloud.com/20160918",
        "2023-04-11,17:33:56 INFO oci_resource_utils.py:206 Listing resource",
        "2023-04-11,17:33:56 INFO base_client.py:565  2023-04-11 17:33:56.232095: Request: GET https://database.eu-stockholm-1.oraclecloud.com/20160918/pluggableDatabases",
        "2023-04-11,17:33:56 DEBUG connectionpool.py:1006 Starting new HTTPS connection (1): database.eu-stockholm-1.oraclecloud.com:443",
        "2023-04-11,17:33:56 DEBUG oci_log_utils.py:84 send: b'CONNECT database.eu-stockholm-1.oraclecloud.com:443 HTTP/1.0\\r\\n\\r\\n'",
        "2023-04-11,17:33:56 DEBUG oci_log_utils.py:84 send: b'GET /20160918/pluggableDatabases?compartmentId=ocid1.compartment.oc1..mycompartmentid&sortBy=PDBNAME&sortOrder=ASC HTTP/1.1\\r\\nuser-agent: Oracle
-PythonSDK/2.98.0 (python 3.9.13; x86_64-Linux) Oracle-Ansible/4.18.0\\r\\naccept-encoding: gzip, deflate\\r\\naccept: application/json\\r\\nconnection: keep-alive\\r\\ncontent-type: application/json\\r\\nopc-client-info: Oracle-PythonSDK/2.98.0\\r\\nopc-
request-id: req-id\\r\\ndate: Tue, 11 Apr 2023 17:33:56 GMT\\r\\nhost: database.eu-stockholm-1.oraclecloud.com\\r\\nauthorization: Signature algorithm=\"rsa-sha256\",headers=\"date (request-target) host\",keyId=\"REMOVED_CONF\",version=\"1\"\\r\\n\\r\\n'",
        "2023-04-11,17:33:57 DEBUG oci_log_utils.py:84 reply: 'HTTP/1.1 400 Bad Request\\r\\n'",
        "2023-04-11,17:33:57 DEBUG oci_log_utils.py:84 header: Date: Tue, 11 Apr 2023 17:33:57 GMT",
        "2023-04-11,17:33:57 DEBUG oci_log_utils.py:84 header: opc-request-id: req-id/req-id2/req-id3",
        "2023-04-11,17:33:57 DEBUG oci_log_utils.py:84 header: Content-Type: application/json",
        "2023-04-11,17:33:57 DEBUG oci_log_utils.py:84 header: X-Content-Type-Options: nosniff",
        "2023-04-11,17:33:57 DEBUG oci_log_utils.py:84 header: Content-Length: 75",
        "2023-04-11,17:33:57 DEBUG connectionpool.py:461 https://database.eu-stockholm-1.oraclecloud.com:443 \"GET /20160918/pluggableDatabases?compartmentId=ocid1.compartment.oc1..sample_compartment&sortBy=PDBNAM
E&sortOrder=ASC HTTP/1.1\" 400 75",
        "2023-04-11,17:33:57 DEBUG base_client.py:594  2023-04-11 17:33:57.395335: time elapsed for request req-id: 1.1631370834074914",
        "2023-04-11,17:33:57 DEBUG base_client.py:609  2023-04-11 17:33:57.395454: Response status: 400",
        "2023-04-11,17:33:57 DEBUG base_client.py:873  2023-04-11 17:33:57.395576: python SDK time elapsed for deserializing: 7.668044418096542e-06",
        "2023-04-11,17:33:57 DEBUG circuit_breaker.py:73 Is transient error status code:400 error code:InvalidParameter",
        "2023-04-11,17:33:57 DEBUG circuit_breaker.py:79 status code:400 not in failure_statuses_and_codes:{409: ['IncorrectState'], 429: [], 500: [], 502: [], 503: [], 504: []}"
    ],
    "opc_request_id": "req-id/req-id2/req-id3",
    "operation_name": "list_pluggable_databases",
    "request_endpoint": "GET https://database.eu-stockholm-1.oraclecloud.com/20160918/pluggableDatabases",
    "service_name": "database",
    "time": "2023-04-11T17:33:57.395519+00:00",
    "troubleshooting_tips": "Refer to troubleshooting guide https://docs.oracle.com/en-us/iaas/tools/oci-ansible-collection/latest/guides/troubleshooting-guide.html"
}

**Comment by manojmeda** [comment] 2023-04-17 08:20
@danidorbek I am able to reproduce the issue. This does not look like an issue with OCI Ansible collection or OCI python SDK. We are sending the request properly but the database service is throwing this error. Please reach out to the database service team.

PS: I see it is happening only when `sort_by` option is passed. So the workaround would be to skip passing the `sort_by` option in the playbook and sort the results using ansible filters. For ex: refer https://stackoverflow.com/questions/51864288/sort-dict-according-to-specific-value-in-ansible.

**Comment by danidorbek** [comment] 2023-04-24 07:25
Thank you, seems removing sort_by can be used as workaround but at end of the day sort_by needs either to be removed from API description or its usage fixed properly.

**Comment by manojmeda** [comment] 2023-05-09 03:41
@danidorbek Agreed. That is the reason i mentioned that as a temporary work around. Please reach out to the database service team for the fix. I am closing this issue since this is not an issue with OCI Ansible.

**Closed by manojmeda** 2023-05-09 03:41 UTC
