### ISSUE TITLE
ExaCC/CS   - ansible module : oracle.oci.oci_database_database

### ISSUE THREAD

**Issue by jewdba** [oracle/oci-ansible-collection#242] opened 2023-09-26 20:45 UTC
## Issue Report

**Describe the issue**

While trying to provision a fresh database on our ExaCC VMcluster the ansible module oracle.oci.oci_database_database used  just returns OK 

**Expected behavior**

Provision a new database according to declared parameters

**Environment**

* OS version: macOS 13.5.1 (22G90)

* Ansible version:

```
# oci-ansible-collection % ansible --version
ansible [core 2.15.3]
  config file = None
  configured module search path = ['/Users/jew/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/8.3.0/libexec/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/jew/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.11.5 (main, Aug 24 2023, 15:18:16) [Clang 14.0.3 (clang-1403.0.22.14.1)] (/usr/local/Cellar/ansible/8.3.0/libexec/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

* OCI Python SDK version:

```
# python -c "import oci;print(oci.__version__)"
2.110.1
```

* OCI Ansible Modules version:

```
# ansible-galaxy collection list oracle.oci

# /<Path>/ansible_collections
Collection Version
---------- -------
oracle.oci 4.28.0
```

**Ansible playbook to reproduce the issue**

```
- name: Deploy Oracle CDB instance
  hosts: localhost
  connection: local
  tasks:
    - name: Deploy CDB
      oracle.oci.oci_database_database:
        compartment_id: ZZZ
        
        database:
          db_name: "CDB1"
          sid_prefix: "CDB1"
          db_unique_name: "CDB1_SITE2"
          admin_password: "Dummy_Passw3rd"
          tde_wallet_password: "Dummy_Passw3rd"
          character_set: "AL32UTF8"
          ncharacter_set: "AL16UTF16"
        source: "NONE"
        db_version: "19.20.0.0.0"
        db_home_id: ZZZ
        state: present
```

**Comment by dineshsuthar786** [comment] 2023-09-27 06:21
@jewdba Thanks for reporting the issue. Can you share the debug logs for this to help us identify the issue. Please refer https://docs.oracle.com/en-us/iaas/tools/oci-ansible-collection/latest/guides/logging-guide.html doc for enabling debug logs.

**Comment by dineshsuthar786** [comment] 2023-10-03 12:09
@jewdba This might be due to oci-ansible-collection's idempotence behaviour. So, I wanted to check if attached debug logs are complete logs? because I don't see relevant logs which tells resource with same attributes is matched with existing resource.

In oci-ansible-collection, Most of the operations are idempotent by design i.e we check whether it is necessary to perform the tasks in the playbook. If there is a matching resource exists with the same attributes provided in playbook, we won't perform the operation and returns Ok. You can read more about the Idempotence behaviour in https://docs.oracle.com/en-us/iaas/tools/oci-ansible-collection/latest/guides/idempotence-guide.html doc.

So, can you check and confirm whether attached logs are complete logs or not.

**Comment by jewdba** [comment] 2023-10-04 18:34
Hi, sorry my fault ... somehow I missed to copy/paste the whole debug log content.

Updated above codebox with the entire content of OCI_ANSIBLE_LOG_DIR logfile  oci_ansible_module.log

I fully understand the principle but here whatever we enter as db_name, db_unique_name. The task returns OK despite we are trying to provision a different database.

According, to the documentation on ExaCC we the module is able to identify on which VMcluster the database should be deployed" using the db_home_id and the db_version attribute.


However, as mentioned earlier and visible in the pool request the db_version attribute is "excluded" of idempotence check.
Resulting in a "false positive"

**Comment by dineshsuthar786** [comment] 2023-10-26 09:40
@jewdba We have fixed the create idempotence issue for `oci_database_database` module in version v4.34.0. Kindly test and let us know if you still face the issue.

**Comment by dineshsuthar786** [comment] 2023-11-03 09:52
@jewdba Closing the issue as we did not get any update from you. Feel free to reopen if you still face the issue.

**Closed by dineshsuthar786** 2023-11-03 09:52 UTC
