### ISSUE TITLE
oci_object_storage_object_facts > object download does not work

### ISSUE THREAD

**Issue by europ** [oracle/oci-ansible-collection#162] opened 2022-06-17 13:09 UTC
### Describe the issue

Download of object from bucket in object storage does not work (does not create the destination file on the host) using `oci_object_storage_object_facts` via `oracle.oci` ansible collection.

Documentation: https://oci-ansible-collection.readthedocs.io/en/latest/collections/oracle/oci/oci_object_storage_object_facts_module.html#ansible-collections-oracle-oci-oci-object-storage-object-facts-module

> PARAMETER['dest'] = The destination file path to write the output. The file will be created if it does not exist. If the file already exists, the content will be overwritten. Required to get a specific object.

### Expected behavior

Download should download the object from bucket in object storage to the destination file path. For instance, object name `object_name` (specified by `oracle.oci.oci_object_storage_object_facts > object_name`) should be downloaded into `/tmp/destination_file_name` (specified by `oracle.oci.oci_object_storage_object_facts > dest`).

### Environment

* OS: Linux
* Python version: 3.10.5
* Ansible version: 2.12.6
* OCI Python SDK version: 2.71.0
* OCI Ansible Modules version: 2.52.0

### Ansible playbook to reproduce the issue

```yml
---
- hosts: localhost
  connection: local
  tasks:
    - name: download specific object from bucket in object storage
      oracle.oci.oci_object_storage_object_facts:
        dest: dest_value
        namespace_name: namespace_name_value
        bucket_name: bucket_name_value
        object_name: object_name_value
```

**Comment by keshavy1894** [comment] 2022-06-20 05:25
@europ Can you Debug Logs?

**Comment by europ** [comment] 2022-06-20 07:43
1. Are you able to reproduce it from the example above ("_Ansible playbook to reproduce the issue_")?
2. I did test this example on the latest versions (python, python sdk, ansible, ansible-module) and the issue is still present (reproducible).
3. Questions like "_Can you Debug Logs?_" are vague and not specific. Please can you be more specific and provide exact commands/instructions what are you requesting to check from my side. I checked system journal, ansible log, please see below.

Record from system journal:
```
ansible-oracle.oci.oci_object_storage_object_facts[8715]: Invoked with
dest=/home/adrian/Downloads/downloaded_file.zip namespace_name=XXX bucket_name=XXX
object_name=XXX auth_type=api_key config_file_location=None config_profile_name=None
api_user=None api_user_fingerprint=NOT_LOGGING_PARAMETER api_user_key_file=None
api_user_key_pass_phrase=NOT_LOGGING_PARAMETER auth_purpose=None tenancy=None
region=None version_id=None range=None opc_sse_customer_algorithm=None
opc_sse_customer_key=NOT_LOGGING_PARAMETER opc_sse_customer_key_sha256=NOT_LOGGING_PARAMETER
http_response_content_disposition=None http_response_cache_control=None
http_response_content_type=None http_response_content_language=None
http_response_content_encoding=None http_response_expires=None prefix=None start=None
end=None delimiter=None fields=None
```

Record from ansible log:
```
2022-06-20 09:12:38,938 p=8596 u=adrian n=ansible | ok: [localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_user": null,
            "api_user_fingerprint": null,
            "api_user_key_file": null,
            "api_user_key_pass_phrase": null,
            "auth_purpose": null,
            "auth_type": "api_key",
            "bucket_name": "XXX",
            "config_file_location": null,
            "config_profile_name": null,
            "delimiter": null,
            "dest": "/home/adrian/Downloads/downloaded_file.zip",
            "end": null,
            "fields": null,
            "http_response_cache_control": null,
            "http_response_content_disposition": null,
            "http_response_content_encoding": null,
            "http_response_content_language": null,
            "http_response_content_type": null,
            "http_response_expires": null,
            "namespace_name": "XXX",
            "object_name": "XXX",
            "opc_sse_customer_algorithm": null,
            "opc_sse_customer_key": null,
            "opc_sse_customer_key_sha256": null,
            "prefix": null,
            "range": null,
            "region": null,
            "start": null,
            "tenancy": null,
            "version_id": null
        }
    },
    "objects": [
        {
            "archival_state": XXX,
            "etag": "XXX",
            "headers": {
                "Content-Length": "XXX",
                "Content-Type": "XXX",
                "accept-ranges": "XXX",
                "access-control-allow-credentials": "XXX",
                "access-control-allow-methods": "XXX",
                "access-control-allow-origin": "XXX",
                "access-control-expose-headers": "XXX",
                "content-md5": "XXX",
                "date": "XXX",
                "etag": "XXX",
                "last-modified": "XXX",
                "opc-request-id": "XXX",
                "storage-tier": "XXX",
                "version-id": "XXX",
                "x-api-id": "XXX"
            },
            "md5": "XXX",
            "name": "XXX",
            "size": XXX,
            "storage_tier": "XXX",
            "time_created": "XXX",
            "time_modified": "XXX"
        }
    ]
}
```

**Comment by sagar2938** [comment] 2022-06-20 09:41
thanks @europ for the info. We couldnt reproduce it in our environment. We are trying it in the environment you have provided. 
In oci modules we have debug logs which get logged only when the debug logs are enabled. You can find the details about how to enable debug logs and where to find the logged log messages  here : https://github.com/oracle/oci-ansible-collection/blob/master/FAQ.md#how-to-enable-debug-mode

please share the debugs logs as well.

**Comment by europ** [comment] 2022-06-20 13:01
> We couldnt reproduce it in our environment.

I think you did a mistake in your test(s). Please, verify the bug report once again.

---

### Test

1. create ansible playbook
    ```yml
    ---
    - hosts: localhost
      connection: local
      tasks:
        - name: download specific object from bucket in object storage
          oracle.oci.oci_object_storage_object_facts:
            dest: /downloaded_file.zip
            namespace_name: namespace_name_value
            bucket_name: bucket_name_value
            object_name: object_name_value
    ```

1. create dockerfile
    ```Dockerfile
    FROM oraclelinux:8

    RUN set -x \
        && dnf -y install oracle-epel-release-el8 \
        && dnf -y group install "Development Tools" \
        && dnf -y install tar openssl-devel libffi-devel \
        && curl -LOJ https://www.python.org/ftp/python/3.10.5/Python-3.10.5.tgz \
        && tar -xzf Python-3.10.5.tgz \
        && cd Python-3.10.5 \
        && ./configure \
        && make \
        && make install \
        && python3.10 -m pip install --upgrade pip setuptools \
        && python3.10 -m pip install oci oci-cli ansible \
        && ansible-galaxy collection install oracle.oci
    ```

1. build docker image
    ```bash
    docker build . -t myimage:latest -f Dockerfile
    ```

1. start docker container
    ```bash
    docker run --rm -it -v $HOME/.oci/config:/root/.oci/config -v $HOME/.oci/oci_private.pem:/home/adrian/.oci/oci_private.pem -v $(pwd)/playbook.yml:/playbook.yml myimage:latest bash
    ```

1. verify container environment
    ```bash
    # check environment version
    cat /etc/os-release

    # check python version
    python --version

    # check ansible version
    ansible --version

    # check oci sdk version
    python -c "import oci;print(oci.__version__)"

    # check oci ansible module version
    ansible-galaxy collection list oracle.oci

    # check the destination file path (downloaded destination path)
    ls -l /downloaded_file.zip
    # EXPECTED RESULT
    #     ls: cannot access '/downloaded_file.zip': No such file or directory
    ```

1. launch ansible playbook
    ```bash
    ansible-playbook /playbook.yml -vvv
    ```

1. verify the downloaded artifact
    ```bash
    ls -l /downloaded_file.zip
    # EXPECTED RESULT
    #     /downloaded_file.zip
    # ACTUAL RESULT
    #     ls: cannot access '/downloaded_file.zip': No such file or directory
    ```

### Result

The expected file is not present locally (is not downloaded).

### Summary

It is a reproducible bug.

**Comment by sagar2938** [comment] 2022-06-21 06:30
@europ , please use the module oracle.oci.oci_object_storage_object  and pass the dest parameter to this module to download the object. You can find the complete details here https://oci-ansible-collection.readthedocs.io/en/latest/collections/oracle/oci/oci_object_storage_object_module.html#ansible-collections-oracle-oci-oci-object-storage-object-module

oci_object_storage_object_facts module is not to download the object currently. We will fix the oci_object_storage_object_facts module in the coming release.

**Comment by europ** [comment] 2022-06-21 07:02
Thank you @sagar2938. Your workaround works perfectly. I will use it until the 2.53.0 version will be released.

**Comment by sagar2938** [comment] 2022-06-21 07:15
@sagar2938 currently we are not targeting it in the next release 2.53.0. We will do it in future release. But you can use this module oci_object_storage_object for downloading object.

**Comment by dineshsuthar786** [comment] 2022-07-04 09:45
@europ As you are able to download the object using `oci_object_storage_object ` module. We have created internal ticket to fix the issue in module `oci_object_storage_object_facts`. Let us know if we can close this issue. We will update you once we fix the issue in module `oci_object_storage_object_facts`.

**Comment by europ** [comment] 2022-07-04 11:59
**As far as I know, bug report (issue) should not be closed until a bug fix is released because others can report the same bug (issue).**

---

So, based on the statement above...

> Let us know if we can close this issue.

Unless the bug fix is not released this issue should not be closed. But, I am not the maintainer of this repository, maintainer is fully authorized to create such decision. If you want to close it, then close it. I would leave it open until a bug fix is released.

**Comment by dineshsuthar786** [comment] 2022-07-29 04:14
@europ We have removed the `dest` param from `oci_object_storage_object_facts` module and updated the documentation in Release v2.55.0. `oci_object_storage_object` module can be used to download or upload the object. We will be closing the issue, feel free to reopen  or create new issue if you still have any problem.

**Closed by dineshsuthar786** 2022-07-29 04:14 UTC
