### ISSUE TITLE
Patching db home with own software image

### ISSUE THREAD

**Issue by ladak44** [oracle/oci-ansible-collection#76] opened 2021-05-13 13:50 UTC
## Issue Report

**Describe the issue**
Hello,
I just try to apply a patch to my db home with module: oci_database_db_home, but i'd like to run PRECHECK.
I run this:

    - name: Patch db home
          oci_database_db_home:
              db_home_id: "{{ item.db_home_id }}"
              patch_details:
                  {database_software_image_id: "ocid1.*****",
                   action: "PRECHECK"
                  }

After this I receive an error, some last lines:

..line 8569, in get_db_home_patch\n    raise ValueError('Parameter {} cannot be None, whitespace or empty string'.format(k))\nValueError: Parameter patchId cannot be None, whitespace or empty string\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

It look like he expects patch_id but i don't have such number.
It works fine with oracle provided images, there is a patch_id which i can provide.
I tried used oci cli and it works fine as well.

export DATABASE_OCID=ocid1.database**********************s3seupojxomo6np2ea
export IMAGE_OCID=ocid1.database****************************qea5ztixz4gqcguq
oci db database patch --database-id $DATABASE_OCID --database-software-image-id $IMAGE_OCID --patch-action PRECHECK

Maybe i use wrong module.

Thank you.

**Expected behavior**

No errors during db home precheck/apply

**Environment**

 uname -a
Linux lxans001p 4.14.35-1844.4.5.el7uek.x86_64 #2 SMP Tue Apr 9 00:29:47 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux

* Ansible version:

(ENV) [a-cke-marclad@lxans001p exa]$ ansible --version
ansible 2.10.4
  config file = /home/statoilfuelretail.com/a-cke-marclad/oci-ansible/exa/ansible_exa.cfg
  configured module search path = ['/usr/share/ansible/collections/ansible_collections/oracle/oci/plugins/modules']
  ansible python module location = /home/ansibleuser/playbooks/exa/ENV/lib64/python3.6/site-packages/ansible
  executable location = /home/ansibleuser/playbooks/exa/ENV/bin/ansible
  python version = 3.6.8 (default, Mar  9 2021, 15:08:44) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44.0.3)]

* OCI Python SDK version:

(ENV) [a-cke-marclad@lxans001p exa]$ python -c "import oci;print(oci.__version__)"
2.38.2

* OCI Ansible Modules version:

# /home/statoilfuelretail.com/a-cke-marclad/.ansible/collections/ansible_collections
Collection Version
---------- -------
oracle.oci 2.19.0

# /usr/share/ansible/collections/ansible_collections
Collection Version
---------- -------
oci.2.20   *
oracle.oci 2.12.0

**Ansible playbook to reproduce the issue**

      - name: Patch db home
          oci_database_db_home:
              db_home_id: "{{ item.db_home_id }}"
              patch_details:
                  {database_software_image_id: "ocid1.*****",
                   action: "PRECHECK"
                  }

**Comment by rohan033** [comment] 2021-05-13 15:39
Hey, Thanks for the detailed explanation. I am looking into it. Will update here soon.

**Comment by manojmeda** [comment] 2021-05-24 03:22
@ladak44 Closing the ticket since the issue is fixed now. Please feel free to reopen or create another issue if you see any issues.

**Closed by manojmeda** 2021-05-24 03:22 UTC
