### ISSUE TITLE
file /tmp/oci_ansible_module.log is being created with the user running playbook can cause permission denied if another user runs the same playbook

### ISSUE THREAD

**Issue by desaes-br** [oracle/oci-ansible-collection#87] opened 2021-06-17 14:52 UTC
## Issue Report

**Describe the issue**

We have a playbook that uses the following code:
 32     - name: List vaults
 33       oci_key_management_vault_facts:
 34         compartment_id: "<OCID>"
 35         auth_type: instance_principal
 36         region: "{{region_identifier}}"
 37       register: list_vault

One use have ran the playbook properly, but then another user in the same team tried to run the same playbook and it failed with permission denied, message:
TASK [List vaults] ****************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 13] Permission denied: '/tmp/oci_ansible_module.log'
fatal: [<host>]: FAILED! => {"changed": false, "module_stderr": "Shared connection to <host> closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/<SECONDUSER>/.ansible/tmp/ansible-tmp-1623940353.624614-69326-207293524412140/AnsiballZ_oci_key_management_vault_facts.py\", line 100, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/<SECONDUSER>/.ansible/tmp/ansible-tmp-1623940353.624614-69326-207293524412140/AnsiballZ_oci_key_management_vault_facts.py\", line 92, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home<SECONDUSER>/.ansible/tmp/ansible-tmp-1623940353.624614-69326-207293524412140/AnsiballZ_oci_key_management_vault_facts.py\", line 41, in invoke_module\r\n    run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\r\n    mod_name, mod_spec, pkg_name, script_name)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_oci_key_management_vault_facts_payload_hyeeyrrd/ansible_oci_key_management_vault_facts_payload.zip/ansible/modules/oci_key_management_vault_facts.py\", line 185, in <module>\r\n  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\r\n  File \"<frozen importlib._bootstrap>\", line 955, in _find_and_load_unlocked\r\n  File \"<frozen importlib._bootstrap>\", line 656, in _load_unlocked\r\n  File \"<frozen importlib._bootstrap>\", line 626, in _load_backward_compatible\r\n  File \"/tmp/ansible_oci_key_management_vault_facts_payload_hyeeyrrd/ansible_oci_key_management_vault_facts_payload.zip/ansible_collections/oracle/oci/plugins/module_utils/oci_common_utils.py\", line 704, in <module>\r\n  File \"/tmp/ansible_oci_key_management_vault_facts_payload_hyeeyrrd/ansible_oci_key_management_vault_facts_payload.zip/ansible_collections/oracle/oci/plugins/module_utils/oci_common_utils.py\", line 598, in get_logger\r\n  File \"/tmp/ansible_oci_key_management_vault_facts_payload_hyeeyrrd/ansible_oci_key_management_vault_facts_payload.zip/ansible_collections/oracle/oci/plugins/module_utils/oci_common_utils.py\", line 654, in setup_logging\r\n  File \"/usr/lib64/python3.6/logging/__init__.py\", line 1808, in basicConfig\r\n    h = FileHandler(filename, mode)\r\n  File \"/usr/lib64/python3.6/logging/__init__.py\", line 1032, in __init__\r\n    StreamHandler.__init__(self, self._open())\r\n  File \"/usr/lib64/python3.6/logging/__init__.py\", line 1061, in _open\r\n    return open(self.baseFilename, self.mode, encoding=self.encoding)\r\nPermissionError: [Errno 13] Permission denied: '/tmp/oci_ansible_module.log'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

The issue is because the first time the user ran the playbook the module created the following file with the permission to 1st user only:
[root@<HOST> ~]# ll /tmp/oci_ansible_module.log
-rw-r--r-- 1 <FIRSTUSER> <GROUP> 0 Jun  8 04:39 /tmp/oci_ansible_module.log

**Expected behavior**

We should either move oci_ansible_module.log under default path (~/.ansible/...) or don't create this file as it can impact the execution of the playbook using oci modules.

**Environment**

* OS version:
Oracle Linux Server release 7.9

* Ansible version:

 ansible --version                                                                                                                                      ok | 29m 50s
ansible [core 2.11.0]
  config file = None
  configured module search path = ['/Users/dsaes/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/4.0.0/libexec/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/dsaes/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.5 (default, May  4 2021, 03:33:11) [Clang 12.0.0 (clang-1200.0.32.29)]
  jinja version = 3.0.1
  libyaml = True

* OCI Python SDK version:

2.26.1+preview.1.0.2464

* OCI Ansible Modules version:

ansible-galaxy collection list                                                                                                                             ok | 13s

# /Users/dsaes/.ansible/collections/ansible_collections
Collection Version
---------- -------
oracle.oci 2.20.0

# /usr/local/Cellar/ansible/4.0.0/libexec/lib/python3.9/site-packages/ansible_collections
Collection                    Version
----------------------------- -------
amazon.aws                    1.5.0
ansible.netcommon             2.0.2
ansible.posix                 1.2.0
ansible.utils                 2.1.0
ansible.windows               1.5.0
arista.eos                    2.1.1
awx.awx                       19.0.0
azure.azcollection            1.5.0
check_point.mgmt              2.0.0
chocolatey.chocolatey         1.1.0
cisco.aci                     2.0.0
cisco.asa                     2.0.1
cisco.intersight              1.0.15
cisco.ios                     2.0.1
cisco.iosxr                   2.1.0
cisco.meraki                  2.2.1
cisco.mso                     1.1.0
cisco.nso                     1.0.3
cisco.nxos                    2.2.0
cisco.ucs                     1.6.0
cloudscale_ch.cloud           2.1.0
community.aws                 1.5.0
community.azure               1.0.0
community.crypto              1.6.2
community.digitalocean        1.1.1
community.docker              1.5.0
community.fortios             1.0.0
community.general             3.0.2
community.google              1.0.0
community.grafana             1.2.1
community.hashi_vault         1.1.3
community.hrobot              1.1.1
community.kubernetes          1.2.1
community.kubevirt            1.0.0
community.libvirt             1.0.1
community.mongodb             1.2.1
community.mysql               2.1.0
community.network             3.0.0
community.okd                 1.1.2
community.postgresql          1.2.0
community.proxysql            1.0.0
community.rabbitmq            1.0.3
community.routeros            1.1.0
community.skydive             1.0.0
community.sops                1.0.6
community.vmware              1.9.0
community.windows             1.3.0
community.zabbix              1.3.0
containers.podman             1.5.0
cyberark.conjur               1.1.0
cyberark.pas                  1.0.6
dellemc.enterprise_sonic      1.0.3
dellemc.openmanage            3.3.0
dellemc.os10                  1.1.1
dellemc.os6                   1.0.7
dellemc.os9                   1.0.4
f5networks.f5_modules         1.9.0
fortinet.fortimanager         2.0.2
fortinet.fortios              2.0.1
frr.frr                       1.0.3
gluster.gluster               1.0.1
google.cloud                  1.0.2
hetzner.hcloud                1.4.3
hpe.nimble                    1.1.3
ibm.qradar                    1.0.3
infinidat.infinibox           1.2.4
inspur.sm                     1.1.4
junipernetworks.junos         2.1.0
kubernetes.core               1.2.1
mellanox.onyx                 1.0.0
netapp.aws                    21.2.0
netapp.azure                  21.5.0
netapp.cloudmanager           21.5.1
netapp.elementsw              21.3.0
netapp.ontap                  21.5.0
netapp.um_info                21.5.0
netapp_eseries.santricity     1.2.7
netbox.netbox                 3.0.0
ngine_io.cloudstack           2.1.0
ngine_io.exoscale             1.0.0
ngine_io.vultr                1.1.0
openstack.cloud               1.4.0
openvswitch.openvswitch       2.0.0
ovirt.ovirt                   1.4.2
purestorage.flasharray        1.8.0
purestorage.flashblade        1.6.0
sensu.sensu_go                1.9.4
servicenow.servicenow         1.0.5
splunk.es                     1.0.2
t_systems_mms.icinga_director 1.16.0
theforeman.foreman            2.0.1
vyos.vyos                     2.2.0
wti.remote                    1.0.1

**Ansible playbook to reproduce the issue**

 32     - name: List vaults
 33       oci_key_management_vault_facts:
 34         compartment_id: "<OCID>"
 35         auth_type: instance_principal
 36         region: "{{region_identifier}}"
 37       register: list_vault

**Comment by bsushant-athena** [comment] 2021-06-18 08:03
We will look into this.

**Comment by bsushant-athena** [comment] 2021-06-23 07:20
@desaes-br  this looks duplicate of this 
https://github.com/oracle/oci-ansible-modules/issues/43
did you set the log_path variable?

Also it seems that whoever runs an ansible playbook first, get’s the ownership of the `/tmp/oci_ansible_module.log`. So if first run is with root, problem occurs.
A workaround would be executing the playbook with sudo  command, "sudo ansible-playbook <playbook.yml>"

**Comment by bsushant-athena** [comment] 2021-07-01 07:35
@desaes-br we have fixed this issue in v2.25.0.

**Closed by bsushant-athena** 2021-07-01 07:35 UTC
